services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=apex
    ports:
      - 5432:5432
    volumes:
      - ./server/pg_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
  # backend:
  #     depends_on:
  #       - postgres
  #       - redis
  #     build: 
  #       context: ./server
  #     ports:
  #       - 3000:3000
  #     restart: unless-stopped
