services:
  nginx:
      build:
        context: .
      ports:
        - 80:80
      restart: unless-stopped
      networks: 
        - public
  backend:
      depends_on:
        - nginx
        - postgres
        - redis
      build: 
        context: ./server
      expose:
        - 3000
      restart: unless-stopped
      networks: 
        - private
        - public
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=apex
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data
    networks: 
      - private
  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    expose:
      - 6379
    networks: 
      - private

networks:
  public: 
    driver: bridge
  private:

volumes:
  data:
